### ISSUE TITLE
Show ServicePoint links and add ServicePoint pages below Service pages

### ISSUE THREAD

**Issue by jbothma** [OpenUpSA/muni-portal-frontend#15]
![Screenshot_2020-10-20_16-59-50](https://user-images.githubusercontent.com/235801/96604679-ab96b400-12f5-11eb-8139-8edddd46e716.png)

**Comment by jbothma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Service points"/"Facilities" contact details](https://trello.com/c/ZnStUNsV/111-service-points-facilities-contact-details)

**Comment by schalkneethling** [comment]
@jbothma I am getting a 500 error for calls such as:

```
https://muni-portal-backend.openup.org.za/api/wagtail/v2/pages/find?html_path=%2Fservices%2Flibraries%2Fbredasdorp-library%2F
```

Is this expected?

**Comment by schalkneethling** [comment]
This is the path that is logged,`/services/libraries/bredasdorp-library/` so, I assume the escaping is the browser and should not matter or affect the end result right?
