### ISSUE TITLE
My Muni tab

### ISSUE THREAD

**Issue by schalkneethling** [OpenUpSA/muni-portal-frontend#18]
Frontend implementation based on components in page and provided information architecture LinkBlocks, headings, overviews.

No category/list toggle yet.

Design referece: https://www.figma.com/file/qJ4OcKo7s9ZNSemeKbgqxv/Citizen-Engagement-App-(Copy)?node-id=321%3A3188

**Comment by jbothma** [comment]
https://trello.com/c/a5J19r5j/105-as-a-user-i-would-like-to-contact-political-and-admin-reps-so-i-can-escalate-an-issue-2-d-jd-2d-matt-1-d-ad

**Comment by schalkneethling** [comment]
Currently the API service for `core.MyMuniPage` returns the following:

```
[
  {
    "id": 11,
    "meta": {
      "type": "core.MyMuniPage",
      "detail_url": "https://muni-portal-backend.openup.org.za/api/wagtail/v2/pages/11/",
      "html_url": "https://cape-agulhas-app.openup.org.za/my-municipality/",
      "slug": "my-municipality",
      "show_in_menus": false,
      "seo_title": "",
      "search_description": "",
      "first_published_at": "2020-10-19T18:54:00.222985Z"
    },
    "title": "My Municipality"
  }
]
```

I assume it is still missing an entry along the lines of:

```
links: [
  {
    title: "Title",
    url: "/service/",
   subjectIconClasses: "",
  }
]
```

**Comment by jbothma** [comment]
You could do https://muni-portal-backend.openup.org.za/api/wagtail/v2/pages/?child_of=11 until we nest child pages in the API

**Comment by jbothma** [comment]
here's a quick crack at API docs https://openup.gitbook.io/cape-agulhas-app/api/overview
