### ISSUE TITLE
Councillor profile photo thumbnail 

### ISSUE THREAD

**Issue by schalkneethling** [OpenUpSA/muni-portal-frontend#29]
Councillor profile photo thumbnail shown on in link block to councillor.

- The template for this exists in the HTML
- Augment the existing `LinkBlock` to conditionally use the standard or thumbnail template based on the presence of a thumbnail image in the `props`

**Comment by schalkneethling** [comment]
@jbothma Let me know when the back-end data is available for this one. Thanks!

**Comment by jbothma** [comment]
https://trello.com/c/uOMcN0eD/149-thumbnails-as-a-user-i-would-like-to-see-someones-face-before-clicking-through-to-their-page-so-that-i-can-see-if-thats-who-i-me

**Comment by jbothma** [comment]
core.CouncillorListPage.child_pages
    core.AdministrationIndexPage.child_pages
    core.CouncillorGroupPage.councillors
    core.ServicePage.head_of_service
