### ISSUE TITLE
Add toggle expanded class in  .rich-text__gradient

### ISSUE THREAD

**Issue by schalkneethling** [OpenUpSA/muni-portal-frontend#41]
Although this issue states that we should toggle the `expanded` class on `.rich-text--expandable`, that is already happening.
I believe the intent here is that, when expanded, the gradient overlay is no longer shown?

The problem here is not the `expanded` class but, some missing CSS and how the DOM is structured.
Currently we have the following:

```
<div class="rich-text rich-text--expandable w-richtext expanded">
    <p>The Cape Agulhas Municipality organisational structure comprises the Office of the
        Municipal Manager and three Directorates.</p>
    <p></p>
    <p>Directorates are headed by a Director who reports to the Municipal Manager. Each
        Directorate is divided into Departments which are headed by a Manager who is
        responsible for specific functions within that Directorate. Cape Agulhas
        Municipality have two divisions within the office of the Municipal Manager that
        are headed by&nbsp;Divisional Heads.</p>
</div>
<div class="rich-text__gradient"></div>
```

> NOTE: We also have an empty paragraph tag in there but, that is probably a CMS issue

Having the `rich-text__gradient` outside the `rich-text` container makes this a bit trickier to solve and one probably need some additional JS however, if we move the `div` inside the container, this is a quick fix. I tried moving the gradient `div` into the container and it still displays correctly.

My proposal to resolve this issue is as follows.

Change the DOM to be as follows:

```
<div class="rich-text rich-text--expandable w-richtext expanded">
...
<div class="rich-text__gradient"></div>
</div>
```

Add the following CSS:

```
.expanded .rich-text__gradient {
    background: none;
}
```

As the `expandable` class is toggled, the gradient will be added and removed as intended.

On a side note, we should probably also add the following:

```
.expandable-rich-text {
    margin-bottom: 24px;
}
```

@jbothma Thoughts?

**Comment by jbothma** [comment]
Looks like we were supposed to put the expanded class on rich-text__gradient and not what I originally said. It uses z-index - that looks like a dirty hack which scares me a bit. But it seems to work for now and I think we need to figure out how to get better at css
